# Generated by Django 5.1.5 on 2025-03-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='title',
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='course_code',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='course_id',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='lecturer_name',
            field=models.CharField(default='Not Assigned', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='registration_number',
            field=models.CharField(default='Not Assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='issue',
            name='subject',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='issue',
            name='user_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='year_of_study',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('CEDAT', 'CEDAT'), ('CONAS', 'CONAS'), ('CEES', 'CEES'), ('CHUSS', 'CHUSS'), ('COBAMS', 'COBAMS'), ('COVAB', 'COVAB'), ('SOL', 'SOL'), ('CAES', 'CAES')], default='Unkwon', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
