# Generated by Django 5.1.5 on 2025-04-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aitsapp', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('submit_issue', 'Can submit issues'), ('view_own_issues', 'Can view own issues'), ('view_assigned_issues', 'Can view assigned issues'), ('update_issue_status', 'Can update issue status'), ('view_all_issues', 'Can view all issues'), ('assign_issues', 'Can assign issues'), ('manage_users', 'Can manage users'), ('configure_settings', 'Can configure settings')]},
        ),
    ]
