# Generated by Django 5.1.5 on 2025-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitsapp', '0008_alter_notification_options_issue_assignment_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(choices=[('COCIS', 'Computing & Information Sciences'), ('CEDAT', 'Engineering, Design, Art & Technology'), ('CONAS', 'Natural Sciences'), ('CEES', 'Education & External Studies'), ('CHUSS', 'Humanities & Social Sciences'), ('COBAMS', 'Business & Management'), ('COVAB', 'Veterinary Medicine'), ('SOL', 'School of Law'), ('CAES', 'Agriculture & Environmental Sciences')], default='Unknown', max_length=50),
        ),
    ]
