# Generated by Django 5.1.5 on 2025-04-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitsapp', '0009_alter_user_managers_alter_user_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('CEDAT', 'CEDAT'), ('CONAS', 'CONAS'), ('CEES', 'CEES'), ('CHUSS', 'CHUSS'), ('COBAMS', 'COBAMS'), ('COVAB', 'COVAB'), ('SOL', 'SOL'), ('CAES', 'CEAS')], default='Unknown', max_length=50),
        ),
    ]
