# Generated by Django 5.1.5 on 2025-04-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitsapp', '0010_alter_user_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='college',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('CEDAT', 'CEDAT'), ('CONAS', 'CONAS'), ('CEES', 'CEES'), ('CHUSS', 'CHUSS'), ('COBAMS', 'COBAMS'), ('COVAB', 'COVAB'), ('SOL', 'SOL'), ('CAES', 'CEAS')], default='UNKNOWN', max_length=50),
        ),
    ]
