# Generated by Django 5.1.5 on 2025-04-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitsapp', '0011_issue_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='college',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('CEDAT', 'CEDAT'), ('CONAS', 'CONAS'), ('CEES', 'CEES'), ('CHUSS', 'CHUSS'), ('COBAMS', 'COBAMS'), ('COVAB', 'COVAB'), ('SOL', 'SOL'), ('CAES', 'CAES')], default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(choices=[('COCIS', 'COCIS'), ('CEDAT', 'CEDAT'), ('CONAS', 'CONAS'), ('CEES', 'CEES'), ('CHUSS', 'CHUSS'), ('COBAMS', 'COBAMS'), ('COVAB', 'COVAB'), ('SOL', 'SOL'), ('CAES', 'CAES')], default='Unknown', max_length=50),
        ),
    ]
