# Generated by Django 5.1.5 on 2025-05-24 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitsapp', '0014_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='subject',
            new_name='course_unit',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='student',
            new_name='submitted_by',
        ),
        migrations.AddField(
            model_name='issue',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aitsapp.department'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aitsapp.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
