# Generated by Django 5.1.5 on 2025-05-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aitsapp', '0015_rename_subject_issue_course_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='submitted_by',
            new_name='student',
        ),
    ]
