# Generated by Django 5.1.5 on 2025-05-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aitsapp', '0016_rename_submitted_by_issue_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_hod',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
